% %% alternative DVV-calculation: if mean of the baseline; 5'' before stimulus 
% % is 0, then all values are replaced by nan, because og infinity problem
% 
% tempCellE = tempCell2;
% for i = 1:size(idxLightsOn,2)/5
%     for ROI = 1:nROIs
%        if mean(tempCell2{i,1}(ROI,1:5),'omitnan')==0
%           tempCellE{i,1}(ROI,:) = nan;
%        elseif mean(tempCell2{i,1}(ROI,:),'omitnan')==0
%           tempCellE{i,1}(ROI,:) = 0; 
%        else 
%           tempCellE{i,1}(ROI,:) = ((tempCell2{i,1}(ROI,:)-...
%               mean(tempCell2{i,1}(ROI,1:5)))./...
%               mean(tempCell2{i,1}(ROI,1:5)))*100;
%           
%        end 
%     end
% end
% 
% f6= figure;
% f6.WindowState='Maximized';
% % sgtitle('dvv velocity, mean response per fish, S heatmap, 5'' before baseline')
% f6 = tiledlayout(2,4); % Requires R2019b or later
% title(f6,['dvv velocity, mean response per fish, S heatmap,',...
%             '5'' before baseline'])
% ylabel(f6,'DVV')
% f6.Padding = 'none';
% 
% for k=1:size(idxLightsOn,2)/5
%     nexttile
%     imagesc(tempCellE{k,1})
%     
%     colormap((jet))
%     colorbar
% %     caxis([0 2000])%ceil(max(max(limitMat)))])
%     
%     title ([tempCell{k, 1}])
%     ylabel('Fish nr.')
%     xlabel('time (s)')
%     box ('off')
%     set(gca,'TickDir','out'); % The only other option is 'in'
%     hold on
% end
% 
% for k=1:size(idxLightsOn,2)/5
%     nexttile
%     rectangle('Position', [6 -4 10 2],'Facecolor',[1 1 0 0.2],'EdgeColor', [1 1 0]), hold on
% 
%     boundedline(1:size(tempCellE{k,1},2),...
%             mean(tempCellE{k,1}(1:length(group1),:),'omitnan'),...
%             ...
%             std((tempCellE{k,1}(1:length(group1),:)),[],1,'omitnan')/...
%             sqrt(length(group1)),'alpha',...
%             1:size(tempCellE{k,1},2),...
%             ...
%             mean(tempCellE{k,1}(...
%             length(group1)+1:length([groups{1,1:2}]),:),'omitnan'),...
%             ...
%             std((tempCellE{k,1}(...
%             length(group1)+1:length([groups{1,1:2}]),:)),[],1,'omitnan')...
%             /sqrt(length(group2)),'alpha',...
%             1:size(tempCellE{k,1},2),...
%             ...
%             mean(tempCellE{k,1}(length([groups{1,1:2}])+1:...
%             length([groups{1,1:3}]),:),'omitnan'),...
%             ...
%             std((tempCellE{k,1}(length([groups{1,1:2}])+1:...
%             length([groups{1,1:3}]),:)),[],1,'omitnan')...
%             /sqrt(length(group3)),'alpha',...
%             1:size(tempCellE{k,1},2),...
%             ...
%             mean(tempCellE{k,1}(length([groups{1,1:3}])+1:...
%             length([groups{1,1:4}]),:),'omitnan'),...
%             ...
%             std((tempCellE{k,1}(length([groups{1,1:3}])+1:...
%             length([groups{1,1:4}]),:)),[],1,'omitnan')...
%             /sqrt(length(group4)),'alpha',...
%             'cmap',C1);
% 
%     legend({'', '', '', '', name_groups{1,1:3} ,''})
%     
%     xlim([1 35])
%     ylim([-100 6000])
%     
%     ylabel('percent change')
%     hold on 
% end
% hold off
% 
% saveas (f6, [folder_path_save,filesep,figures_subfolder,filesep,fish_name,date_exp '_evokedBehaviour_DVV_trad_5sec_S_linePlot_allGroups'  '.fig']);
% saveas (f6, [folder_path_save,filesep,figures_subfolder,filesep,fish_name,date_exp '_evokedBehaviour_DVV_trad_5sec_S_linePlot_allGroups'  '.jpg']);
% saveas (f6, [folder_path_save,filesep,figures_subfolder,filesep,fish_name,date_exp '_evokedBehaviour_DVV_trad_5sec_S_linePlot_allGroups'  '.svg']);
