%% starts running the different functions based on fish_name,
% and thereby group size.


if strcmp(fish_name, 'PTZ')
    [all_fish] = aj_evokedBdeepAnalysis_4groups...
        (all_fish,folder_path_save,fish_name,date_exp,group1,...
        group2,group3, group4, group5,figures_subfolder,...
        group_category,nROIs,groups,name_groups,...
        idxLightsOn,idxLightsOff,...
        threshold,transitionTime);
    
elseif strcmp(fish_name, 'PTZ_short')
    
    [all_fish] = aj_evokedBdeepAnalysis_4groups_25L...
        (all_fish,folder_path_save,fish_name,date_exp,group1,...
        group2,group3, group4, group5,figures_subfolder,...
        group_category,nROIs,groups,name_groups,...
        idxLightsOn,idxLightsOff,...
        threshold,transitionTime);
    
elseif strcmp(fish_name, 'gabra1') || strcmp(fish_name, 'eaat2a') ||...
        strcmp(fish_name, 'scn1lab')
    
    [all_fish] = aj_evokedBdeepAnalysis_3groups...
        (all_fish,folder_path_save,fish_name,date_exp,group1,...
        group2,group3, group4, group5,figures_subfolder,...
        group_category,nROIs,groups,name_groups,...
        idxLightsOn,idxLightsOff,...
        threshold,transitionTime,C1);
elseif strcmp(fish_name, 's280f')
    [all_fish] = aj_evokedBdeepAnalysis_2groups...
        (all_fish,folder_path_save,fish_name,date_exp,group1,...
        group2,group3, group4, group5,figures_subfolder,...
        group_category,nROIs,groups,name_groups,...
        idxLightsOn,idxLightsOff,...
        threshold,transitionTime);
elseif strcmp(fish_name,'PTZ_CPA_4')
    [all_fish] = aj_evokedBdeepAnalysis_7groups_25L...
        (all_fish,folder_path_save,fish_name,date_exp,group1,...
        group2,group3, group4, group5,group6,group7,figures_subfolder,...
        group_category,nROIs,groups,name_groups,...
        idxLightsOn,idxLightsOff,...
        threshold,transitionTime);
end
