%% GLMM for the lightstimulus data; 
%  Generalized mixed-model effect for the light stimulus 
%  Step1: binarize data; either fixed threshold, e.g. 50% dff or the ROC
%  analysis threshold, e.g. 134% for the short PTZ experiment. 
%  Step2: definge variables



burstMat = cell(25,3);
for i=1:size(idxLightsOn,2)
    burstMat{i,1}= ['Stimulation number' num2str(i)];
    
    for ROI=1:nROIs
        t               = 1:floor(max(all_fish{ROI, 1}.t));
        timeLight       = all_fish{ROI, 1}.timestampLight;
        Burst           = all_fish{ROI, 1}.BurstDuration;
        Burst_binary    = all_fish{ROI, 1}.Burst_binary;
        
        
       %% for binary burst data
       temp1   = (Burst_binary(...
            t >= floor(timeLight(idxLightsOn(ROI,i))-5) &...  %% ten seconds before
            t <= floor(timeLight(idxLightsOn(ROI,i))-1) ));
        
        temp2   = (Burst_binary(...
            t >= floor(timeLight(idxLightsOn(ROI,i))) &...
            t <= floor(timeLight(idxLightsOff(ROI,i))+19) )); %% til ten seconds after
        
        T11 = reshape(temp1,[1,5]);
        T12 = interp1(1:length(temp2),temp2,(1:1:30));
        
        temp_total8=[T11,T12];
        burstMat{i,2}(ROI,1:size(temp_total8,2)) = temp_total8;
        
        %% for burst data
       temp5   = (Burst(...
            t >= floor(timeLight(idxLightsOn(ROI,i))-5) &...  %% ten seconds before
            t <= floor(timeLight(idxLightsOn(ROI,i))-1) ));
        
        temp6   = (Burst(...
            t >= floor(timeLight(idxLightsOn(ROI,i))) &...
            t <= floor(timeLight(idxLightsOff(ROI,i))+19) )); %% til ten seconds after
        
        T15 = reshape(temp5,[1,5]);
        T16 = interp1(1:length(temp6),temp6,(1:1:30));
        
        temp_total9=[T15,T16];
        burstMat{i,3}(ROI,1:size(temp_total9,2)) = temp_total9;
        %% empty variables
        temp1  = [];
        temp2  = [];
        temp11 = [];
        temp12 = []; 
        temp_total3 = [];
    end
end

binaryBurst=reshape(burstMat{1,2},[5880 1]);       %% raw DVV
burst = reshape(burstMat{1,3},[5880 1]);            %% binary DVV
timePoint = sort(repmat ([-5 : 29]',168,1));        %% time

light = zeros(168,35); light(:,6:15)=1;
lightCond = reshape(light,[5880 1]);                %% lightsinfo

locs = repmat(repmat([1:24]',7,1),35,1);        %% well number/location
geno = repmat(group_category,35,1);             %% treatment group

group = [1:168]';
group(group1,:)= 1; group(group2,:)= 2; 
group(group3,:)= 3; group(group4,:)= 4; 
group(group5,:)= 1;

groupX = repmat(group,35,1);

fishNum = repmat([1:168]',35,1);

expNum1 = repmat([1:7],24,1); expNum1 = reshape(expNum1,[168,1]);
expNum1 = repmat(expNum1,35,1);

A=table((expNum1),(locs),(fishNum),(groupX),geno,(timePoint),...
    (lightCond),(burst),(binaryBurst),...
    'VariableNames',{'expNum','Location', 'fishNum', 'Treatmentgroup',...
    'Genotype','timePoint', 'Light','BurstDuration', 'BurstBinary'});

A.Genotype = char(A.Genotype);
A.timePointCentered = A.timePoint - mean(unique((A.timePoint)));
A.timeSquared = (A.timePointCentered).^2;

GLME_V_total = fitglme(A,...
    ['BurstDuration  ~ 1 + ',...
    'expNum +',...
    'Location +',...
    'Genotype +',...
    'timePoint +',...
    'Light +',...
    '(1|fishNum)+',...
    '(1|Light:Genotype)+',...
    '(1|timePoint:Genotype)']); %+ (1|Genotype)%     '(1|expNum) +',...
%     '(1|Location) +',...
%     '(1|Light) +',...

%     'timePoint +',...

glmeTOT = fitglme(A,...
          ['BurstDuration ~',...
           'Genotype*timePoint +',...
           'Genotype*timeSquared +',...
           '(1|Location)',...
           ],'Distribution','Normal');


% Before the light stimulus

burstTableBefore    = A(1:840,:);
burstGlmeBefore     = fitglme(burstTableBefore,...
    ['BurstDuration  ~ 1 + ',...
    'expNum +',...
    'Location +',...
    'Genotype +',...
    '(1|fishNum) +',...
    '(1|timePoint) +',....
    '(1|Light)+',...
    '(1|Light:Genotype)+',...
    '(1|timePoint:Genotype)']);

% Light stimulus 

burstTableduring    = A(841:2520,:);
burstGlmeStim       = fitglme(burstTableduring,...
    ['BurstDuration  ~ 1 + ',...
    'expNum +',...
    'Location +',...
    'Genotype +',...
    'timePoint +',....
    '(1|fishNum) +',...
    '(1|Light)+',...
    '(1|Light:Genotype)+',...
    '(1|timePoint:Genotype)']);

% after the light stimulus

burstTableAfter      = A(2521:end,:);
burstGlmeAfter       = fitglme(burstTableAfter,...
    ['BurstDuration  ~ 1 + ',...
    'expNum +',...
    'Location +',...
    'Genotype +',...
    'timePoint +',....
    '(1|fishNum) +',...
    '(1|Light)+',...
    '(1|Light:Genotype)+',...
    '(1|timePoint:Genotype)']);


