function all_fish = AO_aj_loadFiles_20211206(source, folder_path_save, fish_name, ...
    conversion_factor, date_exp, n_row_unn)
%AO_aj_loadFiles_20211206 - Loads the data of Zantics 6 Arena experiments 
%   Syntax:
%       [all_fish] = AO_aj_loadFiles_20211206 (source,timebin,folder_path_save,fish_name,
% conversion_factor,date_exp)
%    
%   Description:
%       loads the data from the exp (csv files generated by Zantics plus the metadata table)
%    
%   Inputs:
%       source - path to the data folders of the exp
%       timebin - timebin value for later binning like velocity
%       folder_path_save - path to where the data will be stored
%       fish_name - Name of the Experiment
%       conversion_factor - conversion factor from pixel to mm 
%       date_exp - date of the experiment
%
%   Outputs:
%       all_fish - cell array with the data of all the fish
%       output2 - Description
%
%   Other m-files required: none
%   Subfunctions: aj_loaddata_20211206
%   MAT-files required: none
%   Author: Anna Maria Ostenrath and Ahmed Jamali 
%   Date : March 2022
% ATTENTION NEEDS TO BE OPTIMIZE FOR OTHER EXP THAN 3 GENOTYPES MGLUR6
stk_files   = dir(fullfile(source, '2022*Exp*'));% NB! remember to change the name of file
tabel_path = dir(fullfile(source, '*.xlsx'));
T = readtable(fullfile(source,tabel_path(1).name));
tic
k = 1;
all_fish = {};
all_fish_temp={};
for i = 1:length(stk_files)
    files = dir(fullfile([source,'\', stk_files(i).name],'*Vibration*.csv'));%!!!!!!!!!!!!!!!!!!!!!!
    for j =1:length(files)
        name_file = [files(j).folder, '\', files(j).name];
        Exp{j, 1} = aj_loaddata_20211206(conversion_factor, name_file, fish_name, ...
            folder_path_save, n_row_unn);
    end
    % here i could put the other info into exp i think in then..n taken from the tabel 
    % cutting the table to the current exp 
    newStr = split(stk_files(i).name,'_');
    exp_name = str2double(newStr{2}(4:end)); %str2double(stk_files(i).name(end));
    cut_T = T(T.Exp == exp_name, :);
    if contains(fish_name, 'Tph2')
        disp(exp_name)
        for fish = 1:6 % should always be six fish for this zantics 
            Exp{1, 1}{fish, 1}.phenotype = cut_T.Phenotype{fish};
            Exp{1, 1}{fish, 1}.group = cut_T.Group(fish);
            Exp{1, 1}{fish, 1}.realNum = cut_T.Fish(fish);
            Exp{1, 1}{fish, 1}.stability = cut_T.Stable_Unstable_1_0_(fish);
            Exp{1, 1}{fish, 1}.exp = cut_T.Exp(fish);
            Exp{1, 1}{fish, 1}.selected = cut_T.Select(fish);
        end
        % here you could put in the metadata for alternative exp (that have 2 groups?)
    end 
    all_fish_temp{k, 1} = Exp; 
    k = k+1;
end
for m = 1:size(all_fish_temp, 1)
    all_fish((m - 1)*6 + 1:m*6, 1) = all_fish_temp{m,1}{1,1};
end 
save([folder_path_save,filesep,fish_name,date_exp '_data.mat'], 'all_fish', '-v7.3');
toc   
clearvars i j k file stk_files name_file k
end
