       fish_name='PTZ_short';
tempCell_V_2_43Hz_mat=tempCell_V_2_43Hz{1,2}; %for PTZ_short
tempCell_V_2_43Hz_mat=tempCell_V_2_43Hz{2,2}; %for other models

       
%% calculate and plot normalized angles
f1= figure;
% %     f1.WindowState='Maximized';
f1=tiledlayout(1,1);%,size(idxLightsOn,2)/5); % Requires R2019b or later
% title(f1,['raw velocity, mean response per fish, S heatmap, 2.43 Hz ',...
%     fish_name])
% ylabel(f1,'Mean velocity (mm/s)')
f1.Padding = 'compact';
f1.TileSpacing = 'compact';
         area([11 11 35 35],[0 60 60 0],'FaceColor',[.8 .8 .8],'FaceAlpha',0.5,'LineStyle','none')
    hold on
       if strcmp(fish_name,'PTZ')||strcmp(fish_name,'PTZ_short')
            for k=1:length(groups)-1
            boundedline(1:size(tempCell_V_2_43Hz_mat,2),...
                (mean(tempCell_V_2_43Hz_mat(groups{1,k},:),'omitnan'))./...
                mean(mean(tempCell_V_2_43Hz_mat(groups{1,k},1:12),'omitnan')),...
                std(tempCell_V_2_43Hz_mat(groups{1,k},:)./mean(mean(tempCell_V_2_43Hz_mat(groups{1,k},1:12)),...
                'omitnan'),[],1,'omitnan')./...
                sqrt(length(group1)),'cmap',C2(k,:))
            end
            hold off
       elseif strcmp(fish_name,'gabra1')||strcmp(fish_name,'eaat2a')
            for k=1:length(groups)-2
            boundedline(1:size(tempCell_V_2_43Hz_mat,2),...
                mean(tempCell_V_2_43Hz_mat(groups{1,k},:),'omitnan')./...
                mean(mean(tempCell_V_2_43Hz_mat(groups{1,k},1:12),'omitnan')),...
                std(tempCell_V_2_43Hz_mat(groups{1,k},:)./mean(mean(tempCell_V_2_43Hz_mat(groups{1,k},1:12))),...
                [],1,'omitnan')./...
                sqrt(length(groups{1,k})),'cmap',C2(k,:))
%          set(gca,'Ycolor','none')
           end
        else
            for k=1:length(groups)-2
            boundedline(1:size(tempCell_V_2_43Hz_mat,2),...
                mean(tempCell_V_2_43Hz_mat(groups{1,k},:),'omitnan')./...
                mean(mean(tempCell_V_2_43Hz_mat(groups{1,k},1:12),'omitnan')),...
                std(tempCell_V_2_43Hz_mat(groups{1,k},:)./mean(mean(tempCell_V_2_43Hz_mat(groups{1,k},1:12))),...
                [],1,'omitnan')./...
                sqrt(length(groups{1,k})),'cmap',C2(k,:))
            end
        end
     box off;
    xlim([0 73]), ylim([0 60])
    set(gca,'Xcolor','none')
