
matAngTemp=cell(height(all_fish),1);
matAng=NaN(height(all_fish),length(all_fish{1,1}.binnedAng2_43));

for r=1:size(matAngTemp,1)
    matAngTemp{r,:}=all_fish{r,1}.binnedAng2_43(1,1:300);
end
matAng2=cell2mat(matAngTemp);



f112= figure;
% %     f1.WindowState='Maximized';
f1=tiledlayout(8,1);%,size(idxLightsOn,2)/5); % Requires R2019b or later
% title(f1,['raw velocity, mean response per fish, S heatmap, 2.43 Hz ',...
%     fish_name])
% ylabel(f1,'Mean velocity (mm/s)')
f1.Padding = 'compact';
f1.TileSpacing = 'compact';

for k=1:1
    nexttile
%     draw=[0 30 13 36];
area([11 11 35 35],[0 30 30 0],'FaceColor',[.8 .8 .8],'FaceAlpha',0.5,'LineStyle','none')
hold on
boundedline(1:size(all_fish{group3', 1}.binnedAng2_43),...
        mean(all_fish{group3', 1}.binnedAng2_43,'omitnan'),...
        std((all_fish{group3', 1}.binnedAng2_43),[],1,'omitnan')./...
        sqrt(length(group3)),'alpha',...
          'cmap',C2);      
    
    
%         1:size(all_fish{k, 1}.binnedAng2_43,2),...
%         mean(all_fish{k, 1}.binnedAng2_43(group2,:),'omitnan'),...
%         std((all_fish{k, 1}.binnedAng2_43(group2,:)),[],1,'omitnan')...
%         ./sqrt(length(group2)),'alpha',...
%         1:size(all_fish{k, 1}.binnedAng2_43,2),...
%         mean(all_fish{k, 1}.binnedAng2_43(group1,:),'omitnan'),...
%         std((all_fish{k, 1}.binnedAng2_43(group1,:)),[],1,'omitnan')...
%         ./sqrt(length(group1)),'alpha',...
%         1:size(all_fish{k, 1}.binnedAng2_43,2),...
%         mean(all_fish{k, 1}.binnedAng2_43(group4,:),'omitnan'),...
%         std((all_fish{k, 1}.binnedAng2_43(group4,:)),[],1,'omitnan')...
%         ./sqrt(length(group4)),'alpha',...
%         'cmap',C2);
    box off;
    xlim([1 292])
    ylim([-1 25])
%     ylabel('Per group')
%     xlabel('time (min)')
    xticks([1,146,292])
    xticklabels({'0','1','2'})
end
set(gca,'FontSize',12);